#
# This file contains configuration flags to customize your site
#

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
title: Brantly Callaway
author: "Brantly Callaway"
defaults:
  # _posts
  - scope:
      path: "/posts/"
      type: posts
    values:
      comments: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      comments: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
comments:
  provider: "disqus"
  disqus:
    shortname: "bcallaway11"